# Nord color scheme for kitty
# https://www.nordtheme.com/

foreground #aeb5c3
background #1a1e26
selection_foreground #1a1e26
selection_background #d8dee9

url_color #88c0d0

# Black
color0 #3b4252
color8 #4c566a

# Red
color1 #bf616a
color9 #bf616a

# Green
color2  #a3be8c
color10 #a3be8c

# Yellow
color3  #ebcb8b
color11 #ebcb8b

# Blue
color4  #81a1c1
color12 #81a1c1

# Magenta
color5  #b48ead
color13 #b48ead

# Cyan
color6  #88c0d0
color14 #8fbcbb

# White
color7  #e5e9f0
color15 #eceff4

# Cursor
cursor #d8dee9
cursor_text_color #1a1e26

# Tab bar
active_tab_foreground   #eceff4
active_tab_background   #1a1e26
inactive_tab_foreground #4c566a
inactive_tab_background #1a1e26
tab_bar_background #3b4252
