[background]
color = Default
bgcolor = Default

[data]
color = Default
bgcolor = Default

[border]
color = Default
bgcolor = Default

[label]
color = Default
bgcolor = Default
attr = bold

[header]
color = Default
bgcolor = Default
attr = bold

[header line]
color = Default
bgcolor = Default

[footer]
color = Default
bgcolor = Default

[footer border]
color = Default
bgcolor = Default

[cursor]
color = Default
bgcolor = Default
attr = reverse

[cursor data]
color = Default
bgcolor = Default
attr = reverse

[cursor border]
color = Default
bgcolor = Default
attr = reverse

[cursor label]
color = Default
bgcolor = Default
attr = reverse bold

[selection]
color = Default
bgcolor = Default
attr = reverse

[title]
color = Default
bgcolor = Default
attr = bold

[status bar]
color = Default
bgcolor = Default
attr = reverse

[pattern]
color = Default
bgcolor = Default
attr = bold underline

[pattern data]
color = Default
bgcolor = Default
attr = bold underline

[error]
color = Default
bgcolor = Default
attr = bold

[input bar]
color = Default
bgcolor = Default

[bookmark]
color = Default
bgcolor = Default
attr = bold

[bookmark line]
color = Default
bgcolor = Default
attr = bold

[cross cursor]
color = Default
bgcolor = Default
attr = reverse

[cross cursor border]
color = Default
bgcolor = Default
attr = reverse
